# Generated by Django 3.1.2 on 2020-10-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20201021_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.DateTimeField(),
        ),
    ]
