# Generated by Django 3.1.2 on 2020-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20201021_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.CharField(max_length=15),
        ),
    ]
